#이름이 왜 필요한가? 왜 로컬에서 부여?

spring:
  application:
    name: mm-gateway-server
  config:
    import: "optional:configserver:http://mm-config-server:1881"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://mm-eureka-server:1761/eureka/